import {
  IconActivity,
  IconActivityHeartbeat,
  IconAlertTriangle,
  IconArrowsExchange,
  IconArrowLeft,
  IconArrowRight,
  IconArticle,
  IconBookmark,
  IconBook2,
  IconBuilding,
  IconBuildingCommunity,
  IconBulb,
  IconCalendarEvent,
  IconChartBar,
  IconChartHistogram,
  IconChartLine,
  IconChecklist,
  IconChevronRight,
  IconCircleCheck,
  IconCircle,
  IconClock,
  IconCode,
  IconCompass,
  IconDatabase,
  IconDatabaseSearch,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconDeviceTablet,
  IconDevices,
  IconEye,
  IconExternalLink,
  IconFileDescription,
  IconFilter,
  IconFingerprint,
  IconFlask2,
  IconHome,
  IconInbox,
  IconInfoCircle,
  IconKey,
  IconLock,
  IconLogout,
  IconMap2,
  IconMapPin,
  IconMessageQuestion,
  IconMenu2,
  IconPointer,
  IconPlugConnected,
  IconRadar2,
  IconRefresh,
  IconRobot,
  IconRoute,
  IconScale,
  IconSearch,
  IconServer,
  IconServer2,
  IconShieldCheck,
  IconShieldLock,
  IconSparkles,
  IconStack2,
  IconTags,
  IconTargetArrow,
  IconTransform,
  IconUser,
  IconUserCode,
  IconUserPlus,
  IconUserSearch,
  IconUserShield,
  IconUsers,
  IconWorld,
  IconX,
  IconCloudUpload,
  IconCoins,
  IconLifebuoy,
  type TablerIcon
} from '@tabler/icons-react';

export type IconName = 'activity' | 'heartbeat' | 'alert' | 'arrowsExchange' | 'arrowLeft' | 'arrowRight' | 'article' | 'bookmark' | 'book' | 'building' | 'buildingCommunity' | 'bulb' | 'calendar' | 'chartBar' | 'chartLine' | 'checklist' | 'external' | 'search' | 'user' | 'close' | 'menu' | 'chevron' | 'circle' | 'clock' | 'cloudUpload' | 'code' | 'coins' | 'database' | 'databaseSearch' | 'desktop' | 'tablet' | 'mobile' | 'eye' | 'filter' | 'fingerprint' | 'flask' | 'info' | 'key' | 'lifebuoy' | 'lock' | 'logout' | 'devices' | 'home' | 'map' | 'mapPin' | 'messageQuestion' | 'pointer' | 'plugConnected' | 'compass' | 'radar' | 'chart' | 'robot' | 'route' | 'scale' | 'target' | 'transform' | 'cycle' | 'document' | 'inbox' | 'layers' | 'server' | 'server2' | 'shield' | 'shieldLock' | 'sparkles' | 'tags' | 'userCode' | 'userPlus' | 'userSearch' | 'userShield' | 'users' | 'world' | 'check';

const icons: Record<IconName, TablerIcon> = {
  activity: IconActivity,
  heartbeat: IconActivityHeartbeat,
  alert: IconAlertTriangle,
  arrowsExchange: IconArrowsExchange,
  arrowLeft: IconArrowLeft,
  arrowRight: IconArrowRight,
  article: IconArticle,
  bookmark: IconBookmark,
  book: IconBook2,
  building: IconBuilding,
  buildingCommunity: IconBuildingCommunity,
  bulb: IconBulb,
  calendar: IconCalendarEvent,
  chartBar: IconChartBar,
  chartLine: IconChartLine,
  checklist: IconChecklist,
  external: IconExternalLink,
  search: IconSearch,
  user: IconUser,
  close: IconX,
  menu: IconMenu2,
  chevron: IconChevronRight,
  circle: IconCircle,
  clock: IconClock,
  code: IconCode,
  cloudUpload: IconCloudUpload,
  coins: IconCoins,
  database: IconDatabase,
  databaseSearch: IconDatabaseSearch,
  desktop: IconDeviceDesktop,
  tablet: IconDeviceTablet,
  mobile: IconDeviceMobile,
  eye: IconEye,
  filter: IconFilter,
  fingerprint: IconFingerprint,
  flask: IconFlask2,
  info: IconInfoCircle,
  key: IconKey,
  lifebuoy: IconLifebuoy,
  lock: IconLock,
  logout: IconLogout,
  devices: IconDevices,
  home: IconHome,
  map: IconMap2,
  mapPin: IconMapPin,
  messageQuestion: IconMessageQuestion,
  pointer: IconPointer,
  plugConnected: IconPlugConnected,
  compass: IconCompass,
  radar: IconRadar2,
  chart: IconChartHistogram,
  robot: IconRobot,
  route: IconRoute,
  scale: IconScale,
  target: IconTargetArrow,
  transform: IconTransform,
  cycle: IconRefresh,
  document: IconFileDescription,
  inbox: IconInbox,
  layers: IconStack2,
  server: IconServer,
  server2: IconServer2,
  shield: IconShieldCheck,
  shieldLock: IconShieldLock,
  sparkles: IconSparkles,
  tags: IconTags,
  userCode: IconUserCode,
  userPlus: IconUserPlus,
  userSearch: IconUserSearch,
  userShield: IconUserShield,
  users: IconUsers,
  world: IconWorld,
  check: IconCircleCheck
};

export default function Icon({ name, size = 18 }: { name: IconName; size?: number }) {
  const Component = icons[name];
  return <Component size={size} stroke={1.8} aria-hidden="true" focusable="false" />;
}
