import {
  IconActivity,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowRight,
  IconArticle,
  IconBookmark,
  IconBook2,
  IconBuilding,
  IconCalendarEvent,
  IconChartBar,
  IconChartHistogram,
  IconChevronRight,
  IconCircleCheck,
  IconCircle,
  IconClock,
  IconCode,
  IconCompass,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconDeviceTablet,
  IconDevices,
  IconEye,
  IconExternalLink,
  IconFileDescription,
  IconFilter,
  IconFlask2,
  IconHome,
  IconInbox,
  IconInfoCircle,
  IconKey,
  IconLock,
  IconLogout,
  IconMap2,
  IconMapPin,
  IconMenu2,
  IconPointer,
  IconRadar2,
  IconRefresh,
  IconSearch,
  IconServer,
  IconShieldCheck,
  IconStack2,
  IconTags,
  IconTargetArrow,
  IconUser,
  IconUserPlus,
  IconUsers,
  IconWorld,
  IconX,
  type TablerIcon
} from '@tabler/icons-react';

export type IconName = 'activity' | 'alert' | 'arrowLeft' | 'arrowRight' | 'article' | 'bookmark' | 'book' | 'building' | 'calendar' | 'chartBar' | 'external' | 'search' | 'user' | 'close' | 'menu' | 'chevron' | 'circle' | 'clock' | 'code' | 'database' | 'desktop' | 'tablet' | 'mobile' | 'eye' | 'filter' | 'flask' | 'info' | 'key' | 'lock' | 'logout' | 'devices' | 'home' | 'map' | 'mapPin' | 'pointer' | 'compass' | 'radar' | 'chart' | 'target' | 'cycle' | 'document' | 'inbox' | 'layers' | 'server' | 'shield' | 'tags' | 'userPlus' | 'users' | 'world' | 'check';

const icons: Record<IconName, TablerIcon> = {
  activity: IconActivity,
  alert: IconAlertTriangle,
  arrowLeft: IconArrowLeft,
  arrowRight: IconArrowRight,
  article: IconArticle,
  bookmark: IconBookmark,
  book: IconBook2,
  building: IconBuilding,
  calendar: IconCalendarEvent,
  chartBar: IconChartBar,
  external: IconExternalLink,
  search: IconSearch,
  user: IconUser,
  close: IconX,
  menu: IconMenu2,
  chevron: IconChevronRight,
  circle: IconCircle,
  clock: IconClock,
  code: IconCode,
  database: IconDatabase,
  desktop: IconDeviceDesktop,
  tablet: IconDeviceTablet,
  mobile: IconDeviceMobile,
  eye: IconEye,
  filter: IconFilter,
  flask: IconFlask2,
  info: IconInfoCircle,
  key: IconKey,
  lock: IconLock,
  logout: IconLogout,
  devices: IconDevices,
  home: IconHome,
  map: IconMap2,
  mapPin: IconMapPin,
  pointer: IconPointer,
  compass: IconCompass,
  radar: IconRadar2,
  chart: IconChartHistogram,
  target: IconTargetArrow,
  cycle: IconRefresh,
  document: IconFileDescription,
  inbox: IconInbox,
  layers: IconStack2,
  server: IconServer,
  shield: IconShieldCheck,
  tags: IconTags,
  userPlus: IconUserPlus,
  users: IconUsers,
  world: IconWorld,
  check: IconCircleCheck
};

export default function Icon({ name, size = 18 }: { name: IconName; size?: number }) {
  const Component = icons[name];
  return <Component size={size} stroke={1.8} aria-hidden="true" focusable="false" />;
}
